"use client";

import { ArrowRight, Building2, Check, Clock3, Code2, Cpu, Github, GraduationCap, ShieldCheck, Terminal, Zap } from "lucide-react";
import { CodeBlock } from "@/components/code-block";
import { FleetCards } from "@/components/fleet-cards";
import { Header } from "@/components/header";
import { IntakeForm } from "@/components/intake-form";
import { Logo } from "@/components/logo";
import { Reveal } from "@/components/reveal";
import { SimulatorBlock } from "@/components/simulator-block";
import { StackDiagram } from "@/components/stack-diagram";
import { useLanguage } from "@/components/language-provider";

const tiers = [
  { icon: GraduationCap, code: "ACADEMIC_01", en: ["Academic & Research", "Semester leases", "Put grant funding into experiments, not depreciating assets. Purpose-built terms for labs and capstone teams.", ["Digital twin included", "University pricing", "ROS onboarding"]], zh: ["學術與研究", "學期租賃", "將補助經費投入實驗，而非折舊資產。為實驗室與專題團隊打造的租賃條款。", ["包含數位孿生", "大學優惠價格", "ROS 導入支援"]], featured: false },
  { icon: Zap, code: "STARTUP_02", en: ["Startup PoC", "3–6 month leases", "Validate the technical thesis, ship the investor demo, and reach your next milestone without a hardware purchase.", ["Production sensor suite", "Rapid replacement SLA", "Flexible extensions"]], zh: ["新創概念驗證", "3–6 個月租賃", "驗證技術假設、完成投資人展示，在不購買硬體的情況下達成下一個里程碑。", ["量產級感測器套件", "快速更換 SLA", "彈性延長租期"]], featured: true },
  { icon: Building2, code: "ENTERPRISE_03", en: ["Enterprise Fleet", "Custom agreements", "Standardized hardware fleets for multi-team autonomy programs, backed by integration engineering.", ["Custom integrations", "24/7 support SLA", "Hardware hot-swaps"]], zh: ["企業機器人車隊", "客製化合約", "為多團隊自主系統計畫提供標準化硬體車隊，並由整合工程支援。", ["客製化整合", "全天候支援 SLA", "硬體快速替換"]], featured: false },
] as const;

function HeroVisual() {
  const { language } = useLanguage(); const zh = language === "zh-Hant";
  return <div className="hero-terminal"><div className="terminal-top"><span>● FLEET_CONTROL</span><span>v2.5.0</span></div><div className="p-5 sm:p-7"><div className="flex justify-between"><div><p className="terminal-label">{zh ? "目前單位" : "ACTIVE UNIT"}</p><h2 className="mt-2 font-mono text-lg text-white">BR-DOG-01</h2></div><span className="online-badge">● {zh ? "線上" : "ONLINE"}</span></div><div className="robot-radar mt-6"><img className="hero-robot-image" src="/images/big-rocket-hero.webp" alt={zh ? "昏暗實驗室中的四足機器人研究平台" : "Four-legged robotics research platform in a dark laboratory"}/><div className="radar-ring ring-one"/><div className="radar-ring ring-two"/><div className="radar-cross x"/><div className="radar-cross y"/><span className="radar-tag left-[5%] top-[12%]">LIDAR // 360°</span><span className="radar-tag bottom-[10%] right-[3%]">IMU // 400Hz</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[[zh ? "電量" : "BATTERY","87%"],["LATENCY","12ms"],[zh ? "狀態" : "STATE",zh ? "就緒" : "READY"]].map(([label,value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="terminal-log"><span>$</span> safety_check --hardware <b>PASS</b><i/></div></div>;
}

export default function Home() {
  const { language } = useLanguage(); const zh = language === "zh-Hant";
  const intakePoints: Array<[typeof Clock3 | typeof Cpu | typeof Code2, string]> = zh ? [[Clock3, "一個工作日內由工程團隊回覆"], [Cpu, "依工作負載配置相符的運算與感測器"], [Code2, "硬體交付前即可使用 SDK 與模擬器"]] : [[Clock3, "Engineering response within one business day"], [Cpu, "Compute and sensor configuration matched to workload"], [Code2, "SDK and simulator access before hardware delivery"]];
  return <main id="top"><Header/>
    <section className="hero-grid relative border-b border-white/[.06] pt-20 sm:pt-28"><div className="hero-glow"/><div className="section-shell relative grid items-center gap-14 pb-20 lg:grid-cols-[1.08fr_.92fr] lg:pb-28"><Reveal><div className="status-pill"><span/> {zh ? "ROS 即用型硬體 · 現正出貨" : "ROS-READY HARDWARE · SHIPPING NOW"}</div><h1 className="mt-8 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-white sm:text-6xl lg:text-[74px]">{zh ? <>別再購買硬體。<br/><span className="text-gradient">開始部署程式碼。</span></> : <>Stop Buying Hardware.<br/><span className="text-gradient">Start Deploying Code.</span></>}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">{zh ? "以彈性訂閱租用 ROS 即用型移動底盤、四足機器人與協作機械臂。預先配置感測器、API 與底層安全急停，讓 AI 團隊專注演算法，而非硬體維護。" : "Rent ROS-ready mobile bases, quadrupeds, and cobots on flexible subscriptions. Pre-configured with sensors, APIs, and low-level safety E-stops so your AI team can focus on algorithms, not hardware maintenance."}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#fleet" className="button-primary button-glow">{zh ? "探索硬體陣容" : "Explore Hardware Fleet"} <ArrowRight className="size-4"/></a><a href="#docs" className="terminal-button"><Terminal className="size-4"/><span>&gt; {zh ? "閱讀文件" : "read docs"}</span></a></div><div className="mt-12 border-t border-white/[.07] pt-6"><p className="mb-4 font-mono text-[10px] uppercase tracking-[.2em] text-slate-600">{zh ? "已驗證生態系" : "Validated ecosystem"}</p><div className="flex flex-wrap gap-x-7 gap-y-4 text-sm font-semibold text-slate-400"><span>ROS <b className="text-blue-400">2</b></span><span>◉ Ubuntu</span><span>NVIDIA JETSON</span><span className="font-mono">GAZEBO_SIM</span></div></div></Reveal><Reveal delay={.12}><HeroVisual/></Reveal></div></section>
    <CodeBlock/><StackDiagram/><SimulatorBlock/><FleetCards/>
    <section id="pricing" className="border-y border-white/[.06] bg-slate-950/45 py-24 sm:py-32"><div className="section-shell"><Reveal><div className="section-heading"><p className="kicker"><span>//</span> LEASING_MODELS</p><h2>{zh ? "讓租賃方案配合你的里程碑。" : "Match the lease to the milestone."}</h2><p className="section-copy">{zh ? "沒有不透明的套裝方案。選擇符合研究週期、資金規劃或車隊藍圖的運作模式。" : "No opaque bundles. Choose the operating model that matches your research cycle, runway, or fleet roadmap."}</p></div></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{tiers.map((tier,index)=>{const { icon: Icon, code, en, zh: zhText } = tier; const featured = tier.featured === true; const [title,term,copy,features]=zh?zhText:en; return <Reveal key={code} delay={index*.08}><article className={`pricing-card ${featured ? "featured" : ""}`}>{featured&&<div className="recommended">{zh ? "最受採用" : "MOST DEPLOYED"}</div>}<div className="flex justify-between"><Icon className="size-5 text-blue-400"/><span className="font-mono text-[10px] text-slate-600">{code}</span></div><h3 className="mt-7 text-xl font-semibold text-white">{title}</h3><p className="mt-2 font-mono text-xs text-blue-400">{term}</p><p className="mt-5 min-h-[90px] text-sm leading-6 text-slate-400">{copy}</p><ul className="space-y-3 border-t border-white/[.07] pt-6">{features.map(feature=><li className="flex gap-3 text-sm text-slate-300" key={feature}><Check className="size-4 text-emerald-400"/>{feature}</li>)}</ul><a href="#intake" className={`${featured?"button-primary":"button-secondary"} mt-8 w-full`}>{zh ? "詢問供應狀況" : "Request availability"} <ArrowRight className="size-4"/></a></article></Reveal>})}</div><p className="mt-6 text-center text-xs text-slate-500"><ShieldCheck className="mr-2 inline size-4"/> {zh ? "需支付可退還的硬體損壞押金，金額依平台而異。" : "Refundable hardware damage deposit required. Amount varies by platform."}</p></div></section>
    <section id="intake" className="section-shell scroll-mt-20 py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.76fr_1.24fr] lg:gap-20"><Reveal><p className="kicker"><span>//</span> REQUEST_DEV_KIT</p><h2 className="section-title">{zh ? "告訴我們你正在打造什麼。" : "Tell us what you're building."}</h2><p className="section-copy">{zh ? "提供工作負載與時程。一位機器人工程師，而非一般業務開發代表，將回覆建議配置與目前供應狀況。" : "Send the workload and timeline. A robotics engineer—not a generic SDR—will return a recommended configuration and current availability."}</p><div className="mt-9 space-y-5">{intakePoints.map(([Icon,text])=><div className="intake-point" key={text as string}><Icon/><span>{text}</span></div>)}</div></Reveal><Reveal delay={.1}><IntakeForm/></Reveal></div></section>
    <footer className="border-t border-white/[.08] bg-black py-12"><div className="section-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><Logo/><p className="mt-3 text-xs text-slate-600">{zh ? "為部署自主系統的團隊提供 ROS 即用型機器人硬體。" : "ROS-ready robotics hardware for teams shipping autonomy."}</p></div><nav aria-label={zh ? "頁尾導覽" : "Footer navigation"} className="flex flex-wrap gap-6 text-sm text-slate-400"><a href="https://github.com/earnmoreclub/robotbusiness"><Github className="mr-1 inline size-4"/> GitHub</a><a href="#docs">{zh ? "API 參考" : "API Reference"}</a><a href="#status">{zh ? "服務狀態" : "Status Page"}</a><a href="#terms">{zh ? "服務條款" : "Terms of Service"}</a><a href="#terms">{zh ? "責任政策" : "Liability Policy"}</a></nav></div><div id="terms" className="mt-10 flex justify-between gap-4 border-t border-white/[.06] pt-6 font-mono text-[10px] uppercase tracking-wider text-slate-700"><span>© 2026 BIG ROCKET SYSTEMS, INC.</span><span>{zh ? "適用硬體損壞與責任條款。" : "Hardware damage and liability clauses apply."}</span></div></div></footer>
  </main>;
}