import { ArrowRight, Building2, Check, Clock3, Code2, Cpu, Github, GraduationCap, ShieldCheck, Terminal, Zap } from "lucide-react";
import { CodeBlock } from "@/components/code-block";
import { FleetCards } from "@/components/fleet-cards";
import { Header } from "@/components/header";
import { IntakeForm } from "@/components/intake-form";
import { Logo } from "@/components/logo";
import { Reveal } from "@/components/reveal";
import { SimulatorBlock } from "@/components/simulator-block";
import { StackDiagram } from "@/components/stack-diagram";

const tiers = [
  { icon: GraduationCap, code: "ACADEMIC_01", title: "Academic & Research", term: "Semester leases", copy: "Put grant funding into experiments, not depreciating assets. Purpose-built terms for labs and capstone teams.", features: ["Digital twin included", "University pricing", "ROS onboarding"] },
  { icon: Zap, code: "STARTUP_02", title: "Startup PoC", term: "3–6 month leases", copy: "Validate the technical thesis, ship the investor demo, and reach your next milestone without a hardware purchase.", features: ["Production sensor suite", "Rapid replacement SLA", "Flexible extensions"], featured: true },
  { icon: Building2, code: "ENTERPRISE_03", title: "Enterprise Fleet", term: "Custom agreements", copy: "Standardized hardware fleets for multi-team autonomy programs, backed by integration engineering.", features: ["Custom integrations", "24/7 support SLA", "Hardware hot-swaps"] },
];
const intakePoints = [{ icon: Clock3, text: "Engineering response within one business day" }, { icon: Cpu, text: "Compute and sensor configuration matched to workload" }, { icon: Code2, text: "SDK and simulator access before hardware delivery" }];

function HeroVisual() { return <div className="hero-terminal"><div className="terminal-top"><span>● FLEET_CONTROL</span><span>v2.5.0</span></div><div className="p-5 sm:p-7"><div className="flex justify-between"><div><p className="terminal-label">ACTIVE UNIT</p><h2 className="mt-2 font-mono text-lg text-white">BR-DOG-01</h2></div><span className="online-badge">● ONLINE</span></div><div className="robot-radar mt-6"><img className="hero-robot-image" src="/images/big-rocket-hero.webp" alt="Four-legged robotics research platform in a dark laboratory"/><div className="radar-ring ring-one"/><div className="radar-ring ring-two"/><div className="radar-cross x"/><div className="radar-cross y"/><span className="radar-tag left-[5%] top-[12%]">LIDAR // 360°</span><span className="radar-tag bottom-[10%] right-[3%]">IMU // 400Hz</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[["BATTERY","87%"],["LATENCY","12ms"],["STATE","READY"]].map(([label,value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div><div className="terminal-log"><span>$</span> safety_check --hardware <b>PASS</b><i/></div></div>; }

export default function Home() {
  return <main id="top"><Header/>
    <section className="hero-grid relative border-b border-white/[.06] pt-20 sm:pt-28"><div className="hero-glow"/><div className="section-shell relative grid items-center gap-14 pb-20 lg:grid-cols-[1.08fr_.92fr] lg:pb-28"><Reveal><div className="status-pill"><span/> ROS-READY HARDWARE · SHIPPING NOW</div><h1 className="mt-8 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] text-white sm:text-6xl lg:text-[74px]">Stop Buying Hardware.<br/><span className="text-gradient">Start Deploying Code.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">Rent ROS-ready mobile bases, quadrupeds, and cobots on flexible subscriptions. Pre-configured with sensors, APIs, and low-level safety E-stops so your AI team can focus on algorithms, not hardware maintenance.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#fleet" className="button-primary button-glow">Explore Hardware Fleet <ArrowRight className="size-4"/></a><a href="#docs" className="terminal-button"><Terminal className="size-4"/><span>&gt; read docs</span></a></div><div className="mt-12 border-t border-white/[.07] pt-6"><p className="mb-4 font-mono text-[10px] uppercase tracking-[.2em] text-slate-600">Validated ecosystem</p><div className="flex flex-wrap gap-x-7 gap-y-4 text-sm font-semibold text-slate-400"><span>ROS <b className="text-blue-400">2</b></span><span>◉ Ubuntu</span><span>NVIDIA JETSON</span><span className="font-mono">GAZEBO_SIM</span></div></div></Reveal><Reveal delay={.12}><HeroVisual/></Reveal></div></section>
    <CodeBlock/><StackDiagram/><SimulatorBlock/><FleetCards/>
    <section id="pricing" className="border-y border-white/[.06] bg-slate-950/45 py-24 sm:py-32"><div className="section-shell"><Reveal><div className="section-heading"><p className="kicker"><span>//</span> LEASING_MODELS</p><h2>Match the lease to the milestone.</h2><p className="section-copy">No opaque bundles. Choose the operating model that matches your research cycle, runway, or fleet roadmap.</p></div></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{tiers.map(({icon:Icon,code,title,term,copy,features,featured},index)=><Reveal key={code} delay={index*.08}><article className={`pricing-card ${featured ? "featured" : ""}`}>{featured&&<div className="recommended">MOST DEPLOYED</div>}<div className="flex justify-between"><Icon className="size-5 text-blue-400"/><span className="font-mono text-[10px] text-slate-600">{code}</span></div><h3 className="mt-7 text-xl font-semibold text-white">{title}</h3><p className="mt-2 font-mono text-xs text-blue-400">{term}</p><p className="mt-5 min-h-[90px] text-sm leading-6 text-slate-400">{copy}</p><ul className="space-y-3 border-t border-white/[.07] pt-6">{features.map(feature=><li className="flex gap-3 text-sm text-slate-300" key={feature}><Check className="size-4 text-emerald-400"/>{feature}</li>)}</ul><a href="#intake" className={`${featured?"button-primary":"button-secondary"} mt-8 w-full`}>Request availability <ArrowRight className="size-4"/></a></article></Reveal>)}</div><p className="mt-6 text-center text-xs text-slate-500"><ShieldCheck className="mr-2 inline size-4"/> Refundable hardware damage deposit required. Amount varies by platform.</p></div></section>
    <section id="intake" className="section-shell scroll-mt-20 py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.76fr_1.24fr] lg:gap-20"><Reveal><p className="kicker"><span>//</span> REQUEST_DEV_KIT</p><h2 className="section-title">Tell us what you&apos;re building.</h2><p className="section-copy">Send the workload and timeline. A robotics engineer—not a generic SDR—will return a recommended configuration and current availability.</p><div className="mt-9 space-y-5">{intakePoints.map(({icon:Icon,text})=><div className="intake-point" key={text}><Icon/><span>{text}</span></div>)}</div></Reveal><Reveal delay={.1}><IntakeForm/></Reveal></div></section>
    <footer className="border-t border-white/[.08] bg-black py-12"><div className="section-shell"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><Logo/><p className="mt-3 text-xs text-slate-600">ROS-ready robotics hardware for teams shipping autonomy.</p></div><nav aria-label="Footer navigation" className="flex flex-wrap gap-6 text-sm text-slate-400"><a href="https://github.com/earnmoreclub/robotbusiness"><Github className="mr-1 inline size-4"/> GitHub</a><a href="#docs">API Reference</a><a href="#status">Status Page</a><a href="#terms">Terms of Service</a><a href="#terms">Liability Policy</a></nav></div><div id="terms" className="mt-10 flex justify-between gap-4 border-t border-white/[.06] pt-6 font-mono text-[10px] uppercase tracking-wider text-slate-700"><span>© 2026 BIG ROCKET SYSTEMS, INC.</span><span>Hardware damage and liability clauses apply.</span></div></div></footer>
  </main>;
}